Add markers docs
mat-docs/Portal.Site pull request #23
Opened 2021-11-23 15:53 UTC by chris-wood-mat

2021-11-24 10:35 UTC, stanislav-domaratsky-mclaren requested changes

2021-11-24 10:35 UTC, stanislav-domaratsky-mclaren commented on docs/manual/articles/markers.md
> +- Description \- A longer form human readable explanation of what the label represents.
"A longer form" might not be the best wording. How about "A detailed, human readable explanation..."?

2021-11-24 10:35 UTC, stanislav-domaratsky-mclaren commented on docs/manual/articles/markers.md
> +None of these properties are required and they can be used in any combination e.g. using only the label or using just the value and units.
I'd better say "None of these properties are **mandatory**"

2021-11-24 10:35 UTC, stanislav-domaratsky-mclaren commented on docs/manual/articles/markers.md
> +            Description = "A average sustained wind speed during this time period",
"**An** average sustained wind speed"

2021-11-24 10:36 UTC, stanislav-domaratsky-mclaren commented
Looks good!

2021-12-22 16:46 UTC, colled approved these changes

2021-12-22 16:47 UTC, merged